# Generated by Django 5.2.17 on 2026-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="external_user_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Instagram IGSID or other channel user id",
                max_length=64,
            ),
        ),
    ]
