# Generated by Django 5.2.17 on 2026-09-03 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("messages_today", models.PositiveIntegerField(default=0)),
                ("ai_answered", models.PositiveIntegerField(default=0)),
                ("human_takeover", models.PositiveIntegerField(default=0)),
                ("new_leads", models.PositiveIntegerField(default=0)),
                ("response_rate", models.FloatField(default=0.0)),
                ("messages_per_day", models.JSONField(blank=True, default=list)),
                ("ai_vs_human", models.JSONField(blank=True, default=dict)),
                ("lead_funnel", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("business", "date")},
            },
        ),
    ]
