# Generated by Django 5.2.17 on 2026-09-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.SlugField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("construction", "Tikinti"),
                            ("medical", "Tibbi"),
                            ("restaurant", "Restoran"),
                            ("real_estate", "Daşınmaz əmlak"),
                            ("beauty", "Gözəllik"),
                            ("legal", "Hüquq"),
                            ("education", "Təhsil"),
                            ("other", "Digər"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("working_hours", models.CharField(blank=True, max_length=200)),
                ("service_areas", models.JSONField(blank=True, default=list)),
                ("speciality", models.JSONField(blank=True, default=list)),
                ("cuisine", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "businesses",
                "ordering": ["name"],
            },
        ),
    ]
