# Generated by Django 5.2.17 on 2026-09-03 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("whatsapp", "WhatsApp"),
                            ("website", "Vebsayt"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Qoşulub"),
                            ("disconnected", "Qoşulmayıb"),
                            ("coming_soon", "Tezliklə"),
                        ],
                        default="disconnected",
                        max_length=32,
                    ),
                ),
                ("handle", models.CharField(blank=True, max_length=120)),
                ("external_id", models.CharField(blank=True, max_length=120)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ["type"],
                "unique_together": {("business", "type")},
            },
        ),
    ]
