# Generated by Django 5.2.17 on 2026-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="access_token",
            field=models.TextField(
                blank=True,
                help_text="Optional override; prefer INSTAGRAM_ACCESS_TOKEN in .env",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Instagram professional account ID",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="status",
            field=models.CharField(
                choices=[
                    ("connected", "Qoşulub"),
                    ("disconnected", "Qoşulmayıb"),
                    ("coming_soon", "Tezliklə"),
                    ("live", "Canlı (Meta API)"),
                ],
                default="disconnected",
                max_length=32,
            ),
        ),
    ]
