# Generated by Django 5.2.17 on 2026-09-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0002_channel_access_token_channel_last_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="access_token",
            field=models.TextField(
                blank=True, help_text="OAuth access token for this channel"
            ),
        ),
    ]
