# Generated by Django 5.2.17 on 2026-09-03 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assistant_name",
                    models.CharField(default="AI Köməkçi", max_length=100),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("az", "Azərbaycan"),
                            ("en", "English"),
                            ("ru", "Русский"),
                        ],
                        default="az",
                        max_length=8,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("friendly", "Dostyana"),
                            ("professional", "Peşəkar"),
                            ("formal", "Rəsmi"),
                            ("casual", "Sərbəst"),
                        ],
                        default="friendly",
                        max_length=32,
                    ),
                ),
                (
                    "response_length",
                    models.CharField(
                        choices=[
                            ("short", "Qısa"),
                            ("medium", "Orta"),
                            ("long", "Ətraflı"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("construction", "Tikinti"),
                            ("medical", "Tibbi"),
                            ("restaurant", "Restoran"),
                            ("real_estate", "Daşınmaz əmlak"),
                            ("beauty", "Gözəllik"),
                            ("legal", "Hüquq"),
                            ("education", "Təhsil"),
                            ("other", "Digər"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("rules", models.TextField(blank=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to="businesses.business",
                    ),
                ),
            ],
        ),
    ]
